name: GachaCrates
description: Create unique crates that offer tiered rewards and incentivize crate openings
version: ${project.version}
api-version: "1.20"
author: Parse
depend: [ PlaceholderAPI ]
main: com.gmail.cparse2021.gachacrates.GachaCrates
commands:
  crate:
    description: Base command for crate management
    aliases: [ gachacrates, gachacrate, crates ]